export type CountryKey = keyof typeof COUNTRIES

export const COUNTRIES = {
  'Burkina Faso': 'Burkina Faso',
  'Central African Republic': 'Central African Republic',
  'DR Congo': 'DR Congo',
  'Ivory Coast': 'Ivory Cast',
  'South Africa': 'South Africa',
  'South Korea': 'Koreya yo hepfo',
  'Sri Lanka': 'Sri Lanka',
  'United Arab Emirates': 'United Arab Emirates',
  'United Kingdom': 'Ubwongereza',
  'United States': 'Reta Zunze Ubumwe za Amerika',
  Australia: 'Australia',
  Austria: 'Austria',
  Belarus: 'Belarus',
  Belgium: 'Ububirigi',
  Benin: 'Benin',
  Burundi: 'Uburundi',
  Cameroon: 'Cameroon',
  Canada: 'Kanada',
  Chad: 'Chad',
  China: 'Ubushinwa',
  Cuba: 'Kuba',
  Cyprus: 'Cyprus',
  Denmark: 'Denmark',
  Egypt: 'Egypt',
  Eritrea: 'Eritrea',
  Ethiopia: 'Ethiopia',
  France: 'Ubufaransa',
  Gabon: 'Gabon',
  Germany: 'Ubudagi',
  Ghana: 'Ghana',
  Guadeloupe: 'Guadeloupe',
  Guinea: 'Guinea',
  Haiti: 'Haiti',
  India: 'Ubuhindi',
  Ireland: 'Ireland',
  Israel: 'Israyeri',
  Italy: 'Ubutariyano',
  Japan: 'Ubuyapani',
  Kenya: 'Kenya',
  Libya: 'Libya',
  Lithuania: 'Lithuania',
  Luxembourg: 'Luxembourg',
  Madagascar: 'Madagascar',
  Malawi: 'Malawi',
  Mali: 'Mali',
  Mauritius: 'Mauritius',
  Mozambique: 'Mozambique',
  Namibia: 'Namibia',
  Netherlands: 'Ubuhorande',
  Niger: 'Niger',
  Nigeria: 'Nigeria',
  Norway: 'Norway',
  Poland: 'Poland',
  Portugal: 'Portugal',
  Romania: 'Romania',
  Russia: 'Uburusiya',
  Rwanda: 'Urwanda',
  Senegal: 'Senegal',
  Serbia: 'Serbia',
  Singapore: 'Singapore',
  Slovakia: 'Slovakia',
  Spain: 'Spain',
  Sudan: 'Sudan',
  Sweden: 'Ubusuwede',
  Switzerland: 'Swise',
  Tanzania: 'Tanzaniya',
  Thailand: 'Thailand',
  Togo: 'Togo',
  Turkey: 'Turukiya',
  Uganda: 'Ubuganda',
  Zambia: 'Zambiya',
  Zimbabwe: 'Zimbabwe',
}
