export type CountryKey = keyof typeof COUNTRIES

export const COUNTRIES = {
  Australia: 'Australia',
  Belarus: 'Belarus',
  Belgium: 'Ububirigi',
  Benin: 'Benin',
  Burundi: 'Uburundi',
  Cameroon: 'Cameroon',
  Canada: 'Kanada',
  'Central African Republic': 'Central African Republi',
  China: 'Ubushinwa',
  Cuba: 'Kuba',
  Cyprus: 'Cyprus',
  'DR Congo': 'DR Congo',
  Denmark: 'Denmark',
  Egypt: 'Egypt',
  Eritrea: 'Eritrea',
  Ethiopia: 'Ethiopia',
  France: 'Ubufaransa',
  Gabon: 'Gabon',
  Germany: 'Ubudagi',
  Ghana: 'Ghana',
  Guadeloupe: 'Guadeloupe',
  India: 'Ubuhindi',
  Ireland: 'Ireland',
  Israel: 'Israyeri',
  Italy: 'Ubutariyano',
  'Ivory Coast': 'Ivory Cast',
  Japan: 'Ubuyapani',
  Kenya: 'Kenya',
  Luxembourg: 'Luxembourg',
  Mali: 'Mali',
  Mauritius: 'Mauritius',
  Netherlands: 'Ubuhorande',
  Niger: 'Niger',
  Norway: 'Norway',
  Poland: 'Poland',
  Portugal: 'Portugal',
  Russia: 'Uburusiya',
  Rwanda: 'Urwanda',
  Senegal: 'Senegal',
  Singapore: 'Singapore',
  'South Africa': 'South Africa',
  'South Korea': 'South Korea',
  Spain: 'Spain',
  Sudan: 'Sudan',
  Sweden: 'Sweden',
  Switzerland: 'Swise',
  Tanzania: 'Tanzaniya',
  Togo: 'Togo',
  Turkey: 'Turukiya',
  Uganda: 'Ubuganda',
  'United Arab Emirates': 'United Arab Emirates',
  'United Kingdom': 'Ubwongereza',
  'United States': 'Reta Zunze Ubumwe za Amerika',
  Zambia: 'Zambiya',
  Zimbabwe: 'Zimbabwe',
}
